apiVersion: v1
kind: Service
metadata:
  name: follow-up-agent
  namespace: default
spec:
  selector:
    app: akabar-follow-up-agent         # This finds the pods labeled "akabar-follow-up-agent" defined above
  ports:
    - protocol: TCP
      port: 8000              # The port the Service listens on
      targetPort: 8000        # The port the Container is listening on
  type: ClusterIP           # Internal only (we will expose it differently later)
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: akabar-follow-up-agent
  namespace: default
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: akabar-follow-up-agent
  template:
    metadata:
      labels:
        app: akabar-follow-up-agent
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: follow-up-agent
        image: mkina66/akabar-follow-up-agent:sha-0b82243
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: akabar-secrets
