apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: default
spec:
  selector:
    app: akabar-redis         # This finds the pods labeled "akabar-redis" defined above
  ports:
    - protocol: TCP
      port: 6379              # The port the Service listens on
      targetPort: 6379        # The port the Container is listening on
  type: ClusterIP           # Internal only (we will expose it differently later)
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: akabar-redis
  namespace: default
spec:
  revisionHistoryLimit: 1
  replicas: 1              # Scale: Run 2 copies (Pods) for high availability
  selector:
    matchLabels:
      app: akabar-redis
  template:
    metadata:
      labels:
        app: akabar-redis
    spec:
      containers:
      - name: redis
        image: redis/redis-stack:latest
        ports:
        - containerPort: 6379