---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgCY+VHL8Nehlf07Ht36QV7Dgj7CHkhSw5WR+wJApYr0asGYd3v3/hpTD2nt/mbrtzSHiB1j4FfZwLKuldAiAif+Xzsxov+jPiXgjUSdQiTOiQT0oMiGCkLAzZIokKUfDM5LNw4ZHA+GK7gFYZiLyxtJBG5fsqcnclIpVFfP8qJuHnjUGXmd97mbDikd/WCnlwVT6+2CH3jbgfFCCPLsAUdiqSTOwieMDz0TlwR1uPjeZVj/8WWR1/kRfBIdEukwAj2/icrMuXuqbUn+mnvjAUgPrSI+c8eTXrA2tZbdvFf2L+J+aTmk09m6FUUR8BLYI6VXzz2j266EdcNO4NK3dX6wMs1fKp5dvcr3RJqWWrFqRNYbrIKgH9X8xSVWXWWIL0QL/gPiMTpQY8YPegPnNtf5jRzygFA6vu8IW9Aionz2HyYgV2ZyYiGYf3CJ63zGcnOT+3OXF6JPdahiB/MWtX1UgLnqN7Ih1/KA0y9Y/3tJETLwpgsNJayraPl5DHl8ymV3szJcHOvqETUaH6nzcb7478WkENyua5T6+AAQWaJE5ETxRAB8SHOQ0HkTg8WyEElwFxsoqrnDF0WEqPY54URiXapNvhOVTrJJhMl35F5kzCGiz2QR7DhI4QnR3H99XOQjINNgIiRJCT1GkkXrz/Q4IwB75ZASUnF98noQaDnHjlZeiBQNMhLf0q2oR9D6L3PJNOA1siqHTbBzu8jbOC3HoOQt8Y9z/h2fmmVCQFhhzJJvO/7b1IELph9NoayGc7mJxjm9o75eoaiwWEKrSzukzR5BVGOE62lPcbHKdhjjLGb+UzNffTxxZDiGUJE9yCGWXmanWJ8Y5PWOhgpWLefqqrUKqGL5wIC8pi+v9xL78fGH8xLKrFFtZBwpUd8qYNjtyGoOmjEvvxEktHA2BwGv1+KP/twgbdI2r63LJWCJLg8yWsKNd5ge5LqqRu73Yl9BZfVoUE5kfiuiPgmOLyQvX88YZUBX
  template:
    metadata:
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
