apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: akabar-web-ingress
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web # Must match your Service name
                port:
                  number: 80
---

apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: default
spec:
  selector:
    app: akabar-web         # This finds the pods labeled "akabar-web" defined above
  ports:
    - protocol: TCP
      port: 80              # The port the Service listens on
      targetPort: 80        # The port the Container is listening on
  type: ClusterIP           # Internal only (we will expose it differently later)
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: akabar-web
  namespace: default
spec:
  revisionHistoryLimit: 1
  replicas: 1               # Scale: Run 2 copies (Pods) for high availability
  selector:
    matchLabels:
      app: akabar-web
  template:
    metadata:
      labels:
        app: akabar-web
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: web
        image: mkina66/akabar-web:sha-7981551
        ports:
        - containerPort: 80
