{
 "title": "akabar",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(http_requests_total,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Resources Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(process_cpu_percent{job=~\"$service\"})",
     "legendFormat": "avg cpu"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(process_memory_percent{job=~\"$service\"})",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "CPU Utilization per Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "process_cpu_percent{job=~\"$service\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory Utilization per Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "process_memory_percent{job=~\"$service\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Performance Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{job=~\"$service\"}[$__range])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Error Rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=~\"$service\", http_status=~\"5..\"}[5m])) by (job) / sum(rate(http_requests_total{job=~\"$service\"}[5m])) by (job) * 100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "http_requests_total{job=~\"$service\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Request Latency [$service]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_latency_seconds_bucket{job=~\"$service\"}[5m])) by (le, job))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_latency_seconds_bucket{job=~\"$service\"}[5m])) by (le, job))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_latency_seconds_bucket{job=~\"$service\"}[5m])) by (le, job))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Request per Second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=~\"$service\"}[5m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "In Progress Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_in_progress{job=~\"$service\"}) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Concurrent Streams",
   "type": "timeseries",
   "description": "A value of 1.0 means: Over the last minute, your service spent an average of one second processing streams for every one second of real-world time. This is equivalent to one stream running continuously.\n\nA value of 0.2 means: The service was busy processing streams for about 20% of the time. This indicates a low workload.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "rate(stream_processing_seconds_total{job=~\"$service\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}